{
  lib,
  stdenv,
  pkg-config,
  wayland,
  freetype,
  fontconfig,
  python3,
}:
stdenv.mkDerivation (finalAttrs: {
  pname = "herdcat";
  version = "0.4.0";
  src = ../.;

  # Build toolchain and dependencies
  # Protocol bindings are pre-generated and committed to git, so
  # wayland-scanner and wayland-protocols are only needed for `make protocols`.
  strictDeps = true;
  nativeBuildInputs = [pkg-config];
  buildInputs = [
    wayland
    freetype
    fontconfig
  ];

  makeFlags = ["release" "PREFIX=$(out)" "INPUT_HELPER_WRAPPER_PATH=/run/wrappers/bin/herdcat-input"];
  installPhase = ''
    runHook preInstall

    # Install binaries
    install -Dm755 build/herdcat $out/bin/${finalAttrs.meta.mainProgram}
    # The store stays unprivileged; NixOS creates the setgid wrapper.
    install -Dm755 build/herdcat-input $out/lib/herdcat/herdcat-input
    install -Dm755 scripts/find_input_devices.sh $out/bin/herdcat-find-devices
    install -Dm755 scripts/herdcat-setup $out/bin/herdcat-setup
    substituteInPlace $out/bin/herdcat-setup \
      --replace-fail '#!/usr/bin/env python3' '#!${python3}/bin/python3'
    install -Dm644 scripts/herdcat_setup_json.py $out/share/herdcat/herdcat_setup_json.py
    for file in integrations/hooks/* integrations/pi/herdcat.ts integrations/opencode/index.js integrations/kitty/* integrations/tmux/*; do
      install -Dm644 "$file" "$out/share/herdcat/$file"
    done
    # User services are generated by the Nix modules.
    
    # Install man page
    install -Dm644 man/herdcat.1 $out/share/man/man1/herdcat.1
    install -Dm644 herdcat.conf.example $out/share/herdcat/herdcat.conf.example

    runHook postInstall
  '';

  # Package information
  meta = {
    description = "Wayland desktop cat that holds up a sign for every coding agent session";
    homepage = "https://github.com/ZChenW/herdcat";
    license = lib.licenses.mit;
    maintainers = [];
    mainProgram = "herdcat";
    platforms = lib.platforms.linux;
  };
})
